import { Follower } from "./types";

export const mockFollowers: Follower[] = [
  {
    id: "1",
    username: "free_likes_promo",
    displayName: "Free Likes",
    botScore: 90,
    isKnownBot: true,
    followerCount: 12,
    followingCount: 7800,
    postCount: 0,
    createdAt: "2024-11-01",
    flaggedFields: ["followers", "following", "posts"],
    reasons: [
      { text: "Known bot account", severity: "high" },
      { text: "Zero posts", severity: "high" },
      { text: "Follows 7800, only 12 followers", severity: "high" },
    ],
  },
  {
    id: "2",
    username: "user_48291047",
    displayName: "user_48291047",
    botScore: 72,
    isKnownBot: false,
    followerCount: 43,
    followingCount: 1900,
    postCount: 2,
    createdAt: "2025-01-15",
    flaggedFields: ["followers", "following", "age"],
    reasons: [
      { text: "Numeric suffix username", severity: "medium" },
      { text: "Very high following-to-follower ratio", severity: "high" },
      { text: "New account (< 90 days)", severity: "medium" },
    ],
  },
  {
    id: "3",
    username: "photography_fan",
    displayName: "Photography Fan",
    botScore: 25,
    isKnownBot: false,
    followerCount: 310,
    followingCount: 480,
    postCount: 18,
    createdAt: "2022-06-10",
    flaggedFields: ["following"],
    reasons: [
      { text: "Slightly high following ratio", severity: "low" },
    ],
  },
  {
    id: "4",
    username: "john.doe",
    displayName: "John Doe",
    botScore: 4,
    isKnownBot: false,
    followerCount: 820,
    followingCount: 390,
    postCount: 145,
    createdAt: "2019-03-22",
    flaggedFields: [],
    reasons: [],
  },
];
